[package]
name = "systest"
version = "0.2.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2021"

[dependencies]
jni-sys = { path = ".." }
libc = "0.2"

[build-dependencies]
ctest2 = "0.4"

[features]
jni19 = []
jni20 = []
jni21 = []